### ISSUE TITLE
.eslintrc duplikater

### ISSUE THREAD

**Issue by LarsGJobloop** [camillab09/React-lists#1]
Ser du har laget noen kopier av **.eslintrc** [1](https://github.com/camillab09/React-lists/blob/4686f9c05a0102c6740b15115c917bf7317d4829/.eslintrc%20copy%202.cjs) [2](https://github.com/camillab09/React-lists/blob/4686f9c05a0102c6740b15115c917bf7317d4829/.eslintrc%20copy.cjs)

Disse skaper litt rot, anbefaler at du sletter disse.

**Comment by camillab09** [comment]
Fikset!
